"""m6 organizations departments permissions user affiliation

Revision ID: a1b508a2c765
Revises: f5a1c3e7b942
Create Date: 2026-08-17 19:29:32.953679

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b508a2c765'
down_revision: str | Sequence[str] | None = 'f5a1c3e7b942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_code', 'organizations', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions_code', 'permissions', ['code'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permission_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_code', name='uq_role_permissions_role_code')
    )
    # SQLite 不支持 ALTER 加约束，users 表变更走 batch 模式（copy-and-move）
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_users_department_id', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_users_organization_id', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_department_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_organization_id', type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('organization_id')
    op.drop_table('role_permissions')
    op.drop_table('departments')
    op.drop_index('ix_permissions_code', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_organizations_code', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
