"""m3 knowledge documents and index jobs

Revision ID: 0b026e5b4905
Revises: 96d6f3784f99
Create Date: 2026-08-17 14:38:15.032781

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = '0b026e5b4905'
down_revision: str | Sequence[str] | None = '96d6f3784f99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('doc_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('uploaded', 'parsing', 'indexing', 'indexed', 'failed', 'outdated')", name='ck_knowledge_documents_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_documents_checksum', 'knowledge_documents', ['checksum'], unique=False)
    op.create_index('ix_knowledge_documents_status', 'knowledge_documents', ['status'], unique=False)
    op.create_table('knowledge_index_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_document_id', sa.Uuid(), nullable=True),
    sa.Column('ai_task_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('indexed_chunks', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action IN ('index', 'reindex', 'delete_index', 'full_rebuild')", name='ck_knowledge_index_jobs_action'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')", name='ck_knowledge_index_jobs_status'),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ),
    sa.ForeignKeyConstraint(['knowledge_document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_index_jobs_ai_task', 'knowledge_index_jobs', ['ai_task_id'], unique=False)
    op.create_index('ix_knowledge_index_jobs_document', 'knowledge_index_jobs', ['knowledge_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_index_jobs_document', table_name='knowledge_index_jobs')
    op.drop_index('ix_knowledge_index_jobs_ai_task', table_name='knowledge_index_jobs')
    op.drop_table('knowledge_index_jobs')
    op.drop_index('ix_knowledge_documents_status', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_checksum', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
