"""m2 records tasks files documents

Revision ID: 96d6f3784f99
Revises: 6e437f847292
Create Date: 2026-08-17 13:53:05.902951

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = '96d6f3784f99'
down_revision: str | Sequence[str] | None = '6e437f847292'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('result_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'queued', 'processing', 'completed', 'failed', 'cancelled')", name='ck_ai_tasks_status'),
    sa.CheckConstraint("task_type IN ('inspection_record_generation', 'photo_report_generation', 'interview_record_generation', 'speech_transcription', 'video_analysis', 'document_generation', 'knowledge_indexing', 'knowledge_reindexing')", name='ck_ai_tasks_task_type'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_ai_tasks_progress'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_tasks_created_by_status_created_at', 'ai_tasks', ['created_by', 'status', 'created_at'], unique=False)
    op.create_index('ix_ai_tasks_status', 'ai_tasks', ['status'], unique=False)
    op.create_index('ix_ai_tasks_task_type', 'ai_tasks', ['task_type'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('video', 'image', 'audio', 'document', 'template', 'generated_document', 'knowledge_source')", name='ck_uploaded_files_category'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_checksum', 'uploaded_files', ['checksum'], unique=False)
    op.create_index('ix_uploaded_files_uploaded_by', 'uploaded_files', ['uploaded_by'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('inspection_record_docx', 'photo_report_docx', 'interview_record_docx', 'inspection_record_pdf', 'photo_report_pdf', 'interview_record_pdf')", name='ck_generated_documents_document_type'),
    sa.CheckConstraint("source_entity_type IN ('inspection_record', 'photo_report', 'interview_record')", name='ck_generated_documents_source_entity_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generated_by_task_id'], ['ai_tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_documents_source_entity', 'generated_documents', ['source_entity_type', 'source_entity_id'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('inspection_unit', sa.String(), nullable=True),
    sa.Column('inspection_address', sa.String(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'processing', 'generated', 'reviewed', 'finalized', 'archived', 'failed')", name='ck_inspection_records_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['ai_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_number')
    )
    op.create_index('ix_inspection_records_created_by', 'inspection_records', ['created_by'], unique=False)
    op.create_index('ix_inspection_records_created_by_status_created_at', 'inspection_records', ['created_by', 'status', 'created_at'], unique=False)
    op.create_index('ix_inspection_records_inspection_date', 'inspection_records', ['inspection_date'], unique=False)
    op.create_index('ix_inspection_records_status', 'inspection_records', ['status'], unique=False)
    op.create_table('interview_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('interviewee_name', sa.String(), nullable=True),
    sa.Column('interviewer_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('structured_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'processing', 'generated', 'reviewed', 'finalized', 'archived', 'failed')", name='ck_interview_records_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['ai_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_records_created_by', 'interview_records', ['created_by'], unique=False)
    op.create_table('photo_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('inspection_unit', sa.String(), nullable=True),
    sa.Column('inspection_address', sa.String(), nullable=True),
    sa.Column('violation_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'processing', 'generated', 'reviewed', 'finalized', 'archived', 'failed')", name='ck_photo_reports_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['ai_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_reports_created_by', 'photo_reports', ['created_by'], unique=False)
    op.create_table('inspection_record_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_record_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('correction_requirement', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("item_type IN ('compliant', 'violation', 'hazard', 'observation', 'recommendation')", name='ck_inspection_record_items_item_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_inspection_record_items_severity'),
    sa.ForeignKeyConstraint(['inspection_record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_report_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_report_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('frame_timestamp', sa.Float(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('detected_address', sa.String(), nullable=True),
    sa.Column('detected_violation', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_report_id'], ['photo_reports.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_report_images')
    op.drop_table('inspection_record_items')
    op.drop_index('ix_photo_reports_created_by', table_name='photo_reports')
    op.drop_table('photo_reports')
    op.drop_index('ix_interview_records_created_by', table_name='interview_records')
    op.drop_table('interview_records')
    op.drop_index('ix_inspection_records_status', table_name='inspection_records')
    op.drop_index('ix_inspection_records_inspection_date', table_name='inspection_records')
    op.drop_index('ix_inspection_records_created_by_status_created_at', table_name='inspection_records')
    op.drop_index('ix_inspection_records_created_by', table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index('ix_generated_documents_source_entity', table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('ix_uploaded_files_uploaded_by', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_checksum', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_ai_tasks_task_type', table_name='ai_tasks')
    op.drop_index('ix_ai_tasks_status', table_name='ai_tasks')
    op.drop_index('ix_ai_tasks_created_by_status_created_at', table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
