"""add idempotency_key to ai_tasks

Revision ID: 2a3bfb83817a
Revises: cadde7f4227b
Create Date: 2026-08-17 00:42:22.981979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3bfb83817a'
down_revision: Union[str, Sequence[str], None] = 'cadde7f4227b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_tasks', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_ai_tasks_idempotency_key'), 'ai_tasks', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_idempotency_key'), table_name='ai_tasks')
    op.drop_column('ai_tasks', 'idempotency_key')
    # ### end Alembic commands ###
