"""initial schema

Revision ID: cadde7f4227b
Revises: 
Create Date: 2026-08-17 00:26:43.336391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cadde7f4227b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('knowledge_index_jobs',
    sa.Column('knowledge_document_id', sa.Uuid(), nullable=True),
    sa.Column('ai_task_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('indexed_chunks', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_index_jobs_ai_task_id'), 'knowledge_index_jobs', ['ai_task_id'], unique=False)
    op.create_index(op.f('ix_knowledge_index_jobs_knowledge_document_id'), 'knowledge_index_jobs', ['knowledge_document_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_tasks',
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('input_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('result_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_type'), 'ai_tasks', ['task_type'], unique=False)
    op.create_table('inspection_records',
    sa.Column('record_number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('inspection_unit', sa.String(length=255), nullable=True),
    sa.Column('inspection_address', sa.String(length=255), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('inspector_names', sa.JSON(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_records_created_by', 'inspection_records', ['created_by'], unique=False)
    op.create_index('ix_inspection_records_inspection_date', 'inspection_records', ['inspection_date'], unique=False)
    op.create_index('ix_inspection_records_status', 'inspection_records', ['status'], unique=False)
    op.create_table('interview_records',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('interviewee_name', sa.String(length=100), nullable=True),
    sa.Column('interviewer_names', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('structured_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_records_created_by', 'interview_records', ['created_by'], unique=False)
    op.create_table('photo_reports',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('inspection_unit', sa.String(length=255), nullable=True),
    sa.Column('inspection_address', sa.String(length=255), nullable=True),
    sa.Column('violation_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_reports_created_by', 'photo_reports', ['created_by'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('storage_provider', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_extension', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_checksum', 'uploaded_files', ['checksum'], unique=False)
    op.create_index('ix_uploaded_files_uploaded_by', 'uploaded_files', ['uploaded_by'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    op.create_table('generated_documents',
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by_task_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_source_entity_id'), 'generated_documents', ['source_entity_id'], unique=False)
    op.create_table('inspection_record_items',
    sa.Column('inspection_record_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('correction_requirement', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_record_id'], ['inspection_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_record_items_inspection_record_id'), 'inspection_record_items', ['inspection_record_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('doc_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_checksum'), 'knowledge_documents', ['checksum'], unique=False)
    op.create_table('photo_report_images',
    sa.Column('photo_report_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=False),
    sa.Column('frame_timestamp', sa.Float(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('detected_address', sa.String(length=255), nullable=True),
    sa.Column('detected_violation', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_report_id'], ['photo_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_report_images_photo_report_id'), 'photo_report_images', ['photo_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_report_images_photo_report_id'), table_name='photo_report_images')
    op.drop_table('photo_report_images')
    op.drop_index(op.f('ix_knowledge_documents_checksum'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_inspection_record_items_inspection_record_id'), table_name='inspection_record_items')
    op.drop_table('inspection_record_items')
    op.drop_index(op.f('ix_generated_documents_source_entity_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('uq_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_uploaded_files_uploaded_by', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_checksum', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_photo_reports_created_by', table_name='photo_reports')
    op.drop_table('photo_reports')
    op.drop_index('ix_interview_records_created_by', table_name='interview_records')
    op.drop_table('interview_records')
    op.drop_index('ix_inspection_records_status', table_name='inspection_records')
    op.drop_index('ix_inspection_records_inspection_date', table_name='inspection_records')
    op.drop_index('ix_inspection_records_created_by', table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_ai_tasks_task_type'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_status'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_index_jobs_knowledge_document_id'), table_name='knowledge_index_jobs')
    op.drop_index(op.f('ix_knowledge_index_jobs_ai_task_id'), table_name='knowledge_index_jobs')
    op.drop_table('knowledge_index_jobs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
