/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegulationQaRouteImport } from './routes/regulation-qa'
import { Route as PhotoReportRouteImport } from './routes/photo-report'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as InterviewRecordRouteImport } from './routes/interview-record'
import { Route as InspectionRecordRouteImport } from './routes/inspection-record'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationQaRoute = RegulationQaRouteImport.update({
  id: '/regulation-qa',
  path: '/regulation-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoReportRoute = PhotoReportRouteImport.update({
  id: '/photo-report',
  path: '/photo-report',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRecordRoute = InterviewRecordRouteImport.update({
  id: '/interview-record',
  path: '/interview-record',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRecordRoute = InspectionRecordRouteImport.update({
  id: '/inspection-record',
  path: '/inspection-record',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspection-record': typeof InspectionRecordRoute
  '/interview-record': typeof InterviewRecordRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/photo-report': typeof PhotoReportRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspection-record': typeof InspectionRecordRoute
  '/interview-record': typeof InterviewRecordRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/photo-report': typeof PhotoReportRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspection-record': typeof InspectionRecordRoute
  '/interview-record': typeof InterviewRecordRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/photo-report': typeof PhotoReportRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inspection-record'
    | '/interview-record'
    | '/knowledge-base'
    | '/photo-report'
    | '/regulation-qa'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inspection-record'
    | '/interview-record'
    | '/knowledge-base'
    | '/photo-report'
    | '/regulation-qa'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/inspection-record'
    | '/interview-record'
    | '/knowledge-base'
    | '/photo-report'
    | '/regulation-qa'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectionRecordRoute: typeof InspectionRecordRoute
  InterviewRecordRoute: typeof InterviewRecordRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  PhotoReportRoute: typeof PhotoReportRoute
  RegulationQaRoute: typeof RegulationQaRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulation-qa': {
      id: '/regulation-qa'
      path: '/regulation-qa'
      fullPath: '/regulation-qa'
      preLoaderRoute: typeof RegulationQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-report': {
      id: '/photo-report'
      path: '/photo-report'
      fullPath: '/photo-report'
      preLoaderRoute: typeof PhotoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-record': {
      id: '/interview-record'
      path: '/interview-record'
      fullPath: '/interview-record'
      preLoaderRoute: typeof InterviewRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-record': {
      id: '/inspection-record'
      path: '/inspection-record'
      fullPath: '/inspection-record'
      preLoaderRoute: typeof InspectionRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectionRecordRoute: InspectionRecordRoute,
  InterviewRecordRoute: InterviewRecordRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  PhotoReportRoute: PhotoReportRoute,
  RegulationQaRoute: RegulationQaRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
