/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegulationQaRouteImport } from './routes/regulation-qa'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoReportIndexRouteImport } from './routes/photo-report/index'
import { Route as InterviewRecordIndexRouteImport } from './routes/interview-record/index'
import { Route as InspectionRecordIndexRouteImport } from './routes/inspection-record/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PhotoReportIdRouteImport } from './routes/photo-report/$id'
import { Route as InterviewRecordIdRouteImport } from './routes/interview-record/$id'
import { Route as InspectionRecordIdRouteImport } from './routes/inspection-record/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPromptsRouteImport } from './routes/admin/prompts'
import { Route as AdminPluginsRouteImport } from './routes/admin/plugins'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminEvaluationsRouteImport } from './routes/admin/evaluations'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationQaRoute = RegulationQaRouteImport.update({
  id: '/regulation-qa',
  path: '/regulation-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoReportIndexRoute = PhotoReportIndexRouteImport.update({
  id: '/photo-report/',
  path: '/photo-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRecordIndexRoute = InterviewRecordIndexRouteImport.update({
  id: '/interview-record/',
  path: '/interview-record/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRecordIndexRoute = InspectionRecordIndexRouteImport.update({
  id: '/inspection-record/',
  path: '/inspection-record/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoReportIdRoute = PhotoReportIdRouteImport.update({
  id: '/photo-report/$id',
  path: '/photo-report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRecordIdRoute = InterviewRecordIdRouteImport.update({
  id: '/interview-record/$id',
  path: '/interview-record/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRecordIdRoute = InspectionRecordIdRouteImport.update({
  id: '/inspection-record/$id',
  path: '/inspection-record/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/admin/prompts',
  path: '/admin/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPluginsRoute = AdminPluginsRouteImport.update({
  id: '/admin/plugins',
  path: '/admin/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationsRoute = AdminEvaluationsRouteImport.update({
  id: '/admin/evaluations',
  path: '/admin/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inspection-record/$id': typeof InspectionRecordIdRoute
  '/interview-record/$id': typeof InterviewRecordIdRoute
  '/photo-report/$id': typeof PhotoReportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/inspection-record/': typeof InspectionRecordIndexRoute
  '/interview-record/': typeof InterviewRecordIndexRoute
  '/photo-report/': typeof PhotoReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inspection-record/$id': typeof InspectionRecordIdRoute
  '/interview-record/$id': typeof InterviewRecordIdRoute
  '/photo-report/$id': typeof PhotoReportIdRoute
  '/admin': typeof AdminIndexRoute
  '/inspection-record': typeof InspectionRecordIndexRoute
  '/interview-record': typeof InterviewRecordIndexRoute
  '/photo-report': typeof PhotoReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/regulation-qa': typeof RegulationQaRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inspection-record/$id': typeof InspectionRecordIdRoute
  '/interview-record/$id': typeof InterviewRecordIdRoute
  '/photo-report/$id': typeof PhotoReportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/inspection-record/': typeof InspectionRecordIndexRoute
  '/interview-record/': typeof InterviewRecordIndexRoute
  '/photo-report/': typeof PhotoReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/regulation-qa'
    | '/settings'
    | '/tasks'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/evaluations'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/plugins'
    | '/admin/prompts'
    | '/admin/users'
    | '/inspection-record/$id'
    | '/interview-record/$id'
    | '/photo-report/$id'
    | '/admin/'
    | '/inspection-record/'
    | '/interview-record/'
    | '/photo-report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/regulation-qa'
    | '/settings'
    | '/tasks'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/evaluations'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/plugins'
    | '/admin/prompts'
    | '/admin/users'
    | '/inspection-record/$id'
    | '/interview-record/$id'
    | '/photo-report/$id'
    | '/admin'
    | '/inspection-record'
    | '/interview-record'
    | '/photo-report'
  id:
    | '__root__'
    | '/'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/regulation-qa'
    | '/settings'
    | '/tasks'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/evaluations'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/plugins'
    | '/admin/prompts'
    | '/admin/users'
    | '/inspection-record/$id'
    | '/interview-record/$id'
    | '/photo-report/$id'
    | '/admin/'
    | '/inspection-record/'
    | '/interview-record/'
    | '/photo-report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegulationQaRoute: typeof RegulationQaRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEvaluationsRoute: typeof AdminEvaluationsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPluginsRoute: typeof AdminPluginsRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InspectionRecordIdRoute: typeof InspectionRecordIdRoute
  InterviewRecordIdRoute: typeof InterviewRecordIdRoute
  PhotoReportIdRoute: typeof PhotoReportIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InspectionRecordIndexRoute: typeof InspectionRecordIndexRoute
  InterviewRecordIndexRoute: typeof InterviewRecordIndexRoute
  PhotoReportIndexRoute: typeof PhotoReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulation-qa': {
      id: '/regulation-qa'
      path: '/regulation-qa'
      fullPath: '/regulation-qa'
      preLoaderRoute: typeof RegulationQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-report/': {
      id: '/photo-report/'
      path: '/photo-report'
      fullPath: '/photo-report/'
      preLoaderRoute: typeof PhotoReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-record/': {
      id: '/interview-record/'
      path: '/interview-record'
      fullPath: '/interview-record/'
      preLoaderRoute: typeof InterviewRecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-record/': {
      id: '/inspection-record/'
      path: '/inspection-record'
      fullPath: '/inspection-record/'
      preLoaderRoute: typeof InspectionRecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-report/$id': {
      id: '/photo-report/$id'
      path: '/photo-report/$id'
      fullPath: '/photo-report/$id'
      preLoaderRoute: typeof PhotoReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-record/$id': {
      id: '/interview-record/$id'
      path: '/interview-record/$id'
      fullPath: '/interview-record/$id'
      preLoaderRoute: typeof InterviewRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-record/$id': {
      id: '/inspection-record/$id'
      path: '/inspection-record/$id'
      fullPath: '/inspection-record/$id'
      preLoaderRoute: typeof InspectionRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/admin/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plugins': {
      id: '/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AdminPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluations': {
      id: '/admin/evaluations'
      path: '/admin/evaluations'
      fullPath: '/admin/evaluations'
      preLoaderRoute: typeof AdminEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegulationQaRoute: RegulationQaRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEvaluationsRoute: AdminEvaluationsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPluginsRoute: AdminPluginsRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InspectionRecordIdRoute: InspectionRecordIdRoute,
  InterviewRecordIdRoute: InterviewRecordIdRoute,
  PhotoReportIdRoute: PhotoReportIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  InspectionRecordIndexRoute: InspectionRecordIndexRoute,
  InterviewRecordIndexRoute: InterviewRecordIndexRoute,
  PhotoReportIndexRoute: PhotoReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
